#!/bin/bash

# nitrogen --restore &

xmodmap -e 'keycode 66 = Control_L'
xmodmap -e 'clear Lock'
xmodmap -e 'add Control = Control_L'

feh  --bg-scale '/home/pankaj/scripts/wallpaper/wallpaper.jpg' & 

# gnome-terminal -e "python fire.py" &

#./.wallpaper/wallpaper.sh

trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10% --tint 0x000000 --transparent true --alpha 0 --height 14 &

if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi
 
if [ -x /usr/bin/gnome-power-manager ] ; then
   sleep 3
   gnome-power-manager &
fi

xpad --show &

exec xmonad