#!/bin/bash

# nitrogen --restore &

xsetroot -cursor_name left_ptr

xmodmap -e 'keycode 66 = Control_L'
xmodmap -e 'clear Lock'
xmodmap -e 'add Control = Control_L'

# turn off the annoying beep beep
xset b off

# feh  --bg-scale '/home/pankaj/scripts/wallpaper/wallpaper.jpg' & 
feh --bg-scale '/home/pankaj/.wallpaper' &

# gnome-terminal -e "python fire.py" &

#./.wallpaper/wallpaper.sh

trayer --edge top --align right --SetDockType true --SetPartialStrut false --expand true --width 10% --tint 0x000000 --transparent true --alpha 0 --height 14 &

dropboxd &

#if [ -x /usr/bin/nm-applet ] ; then
 #  nm-applet --sm-disable &
#fi
 
#if [ -x /usr/bin/gnome-power-manager ] ; then
 #  sleep 3
  # gnome-power-manager &
#fi


# xpad --show &
# firefox &
# skype &
# pidgin &
# spotify &

exec xmonad
